### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by jacobfrye-1** [lixuy/vlmcsd#1]
Please provide the complete source of the git including contents of bin, build and lib folder.

**Comment by lixuy** [comment]
This is the target folder for compiling the generated files, not the folder where the source code is stored.
Ignore everything in both directory.

**Comment by jacobfrye-1** [comment]
But then how do you 'make' it in Linux?
I am using Ubuntu with GCC and it shows error everytime I use 'make'. When I resolve one error another pops up to take it's place. Is there something I am doing wrong?
